Dealing with Duplicate values,Missing Data

In [2]:
import pandas as pd

Duplicate values

In [ ]:
cdata = pd.read_csv("subdata_pandas/company.csv")
cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [13]:
import os

print(os.getcwd())
print(os.listdir())

/Users/rijeshs/placementtrinning
['tuple.ipynb', '.DS_Store', 'Untitled.ipynb', 'practice.ipynb', '.gitignore', '.venv', '.ipynb_checkpoints', 'pandasphase2.ipynb', '.git', 'pandas']

In [16]:
import pandas as pd

cdata = pd.read_csv("pandas/company.csv")

cdata

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

In [17]:
cdata.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [18]:
cdata[cdata.duplicated()]

    EEID   Name gender   salary
6  EMP02  rohit      M  25000.0

In [19]:
cdata.duplicated().sum()

np.int64(1)

Missing values

In [21]:
cdata.isnull().sum()

EEID      0
Name      1
gender    1
salary    2
dtype: int64

In [27]:
cdata['salary'].fillna(cdata['salary'].mean())

0    24400.0
1    25000.0
2    27000.0
3    20000.0
4    25000.0
5    24400.0
6    25000.0
Name: salary, dtype: float64