In [1]:
import pandas as pd

In [3]:
sdata=pd.read_csv("subdata_pandas/student1.csv")
sdata

    id firstName  lastName  age  marks   fees
0  101    Akshay    Shetty   20     85  25000
1  102    Ananya       Rao   21     92  30000
2  103     Rohit  Bhandary   19     76  28000
3  104     Nisha   D'Souza   20     88  25000
4  105   Karthik   Poojary   22     69  32000
5  106    Shreya    Shetty   19     95  30000
6  107     Rohan      Naik   21     72  27000
7  108   Deepika      Bhat   20     81  28000
8  109  Abhishek    Kotian   22     64  26000
9  110     Pooja       Rai   19     90  30000

In [4]:
sdata[["id","firstName"]]

    id firstName
0  101    Akshay
1  102    Ananya
2  103     Rohit
3  104     Nisha
4  105   Karthik
5  106    Shreya
6  107     Rohan
7  108   Deepika
8  109  Abhishek
9  110     Pooja

In [11]:
sdata.loc[sdata.firstName=="Rohan"]

    id firstName lastName  age  marks   fees
6  107     Rohan     Naik   21     72  27000

In [12]:
sdata.iloc[0:2,0:2]

    id firstName
0  101    Akshay
1  102    Ananya

In [22]:
sdata['age']>20
sdata[sdata['age']>20]
student_age_filter = sdata[sdata['age']>20]
student_age_filter

    id firstName lastName  age  marks   fees
1  102    Ananya      Rao   21     92  30000
4  105   Karthik  Poojary   22     69  32000
6  107     Rohan     Naik   21     72  27000
8  109  Abhishek   Kotian   22     64  26000

In [23]:
sdata["fullName"] = sdata['firstName']+" "+sdata["lastName"]
sdata

    id firstName  lastName  age  marks   fees         fullName
0  101    Akshay    Shetty   20     85  25000    Akshay Shetty
1  102    Ananya       Rao   21     92  30000       Ananya Rao
2  103     Rohit  Bhandary   19     76  28000   Rohit Bhandary
3  104     Nisha   D'Souza   20     88  25000    Nisha D'Souza
4  105   Karthik   Poojary   22     69  32000  Karthik Poojary
5  106    Shreya    Shetty   19     95  30000    Shreya Shetty
6  107     Rohan      Naik   21     72  27000       Rohan Naik
7  108   Deepika      Bhat   20     81  28000     Deepika Bhat
8  109  Abhishek    Kotian   22     64  26000  Abhishek Kotian
9  110     Pooja       Rai   19     90  30000        Pooja Rai