DATA FARAMES

In [3]:
import pandas as pd

In [10]:
data={
    "name":["rijesh","pranav","rohan"],
    "age":[20,21,22],
    "city":["surathkal","udupi","udupi"]

}
df = pd.DataFrame(data)
df

     name  age       city
0  rijesh   20  surathkal
1  pranav   21      udupi
2   rohan   22      udupi

SHAPE

In [13]:
#shape
df.shape
#size
df.size
#colums
df.columns
#rename
df.rename(columns={"age":"student_age"},inplace=True)
df

     name  student_age       city
0  rijesh           20  surathkal
1  pranav           21      udupi
2   rohan           22      udupi

### Export to csv file

In [ ]:
df.to_csv("student_data.csv")
df

     name  student_age       city
0  rijesh           20  surathkal
1  pranav           21      udupi
2   rohan           22      udupi

In [16]:
df=pd.read_excel("expense.xlsx")
df

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

Exploring Data

In [18]:
df=pd.read_csv("subdata_pandas/employee.csv")
df

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

Check Top 10 rows

In [20]:
df.head(10)
#df.tail(10)

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
5,6,Male,22-08-1958,15,Sales,32100,13500,8.17,5.58,No
6,7,Male,26-04-1956,15,IT,36000,18750,8.17,9.50,No
7,8,Female,06-05-1966,12,Finance,21900,9750,8.17,NaN,No
8,9,Female,23-01-1946,15,Accounting,27900,12750,8.17,9.58,No
9,10,Female,13-02-1946,12,Finance,24000,13500,8.17,20.33,No

Check last (10)

In [21]:
df.tail(10)

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
464,465,Male,20-07-1962,12,Engineering,33900,16500,5.33,8.83,No
465,466,Female,15-06-1948,12,Engineering,23400,13500,5.33,16.50,No
466,467,Female,18-08-1967,16,IT,32850,19500,5.33,1.67,No
467,468,Female,28-11-1965,16,Engineering,55750,19980,5.33,3.00,No
468,469,Female,01-06-1964,15,Accounting,25200,13950,5.33,4.75,No
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

Shape And Size

In [23]:
df.shape
df.size

4740

Info

In [24]:
df.info

<bound method DataFrame.info of       id  gender dateofbirth  education   department  salary  starting_salary  \
0      1    Male  03-02-1952         15           IT   57000            27000
1      2    Male  23-05-1958         16           IT   40200            18750
2      3  Female  26-07-1929         12      Finance   21450            12000
3      4  Female  15-04-1947         18           IT   21900            13200
4      5    Male  09-02-1955         15      Finance   45000            21000
..   ...     ...         ...        ...          ...     ...              ...
469  470    Male  22-01-1964         12           IT   26250            15750
470  471    Male  03-08-1966         15  Engineering   26400            15750
471  472    Male  21-02-1966         15        Sales   39150            15750
472  473  Female  25-11-1937         12    Marketing   21450            12750
473  474  Female  05-11-1968         12           IT   29400            14250

     job_time  previous_experience minority
0        8.17                  NaN       No
1        8.17                 3.00       No
2        8.17                31.75       No
3        8.17                15.83       No
4        8.17                11.50       No
..        ...                  ...      ...
469      5.33                 5.75      Yes
470      5.33                 2.67      Yes
471      5.25                 3.83       No
472      5.25                11.58       No
473      5.25                 0.75       No

[474 rows x 10 columns]>

Describe

In [26]:
df.describe

<bound method NDFrame.describe of       id  gender dateofbirth  education   department  salary  starting_salary  \
0      1    Male  03-02-1952         15           IT   57000            27000
1      2    Male  23-05-1958         16           IT   40200            18750
2      3  Female  26-07-1929         12      Finance   21450            12000
3      4  Female  15-04-1947         18           IT   21900            13200
4      5    Male  09-02-1955         15      Finance   45000            21000
..   ...     ...         ...        ...          ...     ...              ...
469  470    Male  22-01-1964         12           IT   26250            15750
470  471    Male  03-08-1966         15  Engineering   26400            15750
471  472    Male  21-02-1966         15        Sales   39150            15750
472  473  Female  25-11-1937         12    Marketing   21450            12750
473  474  Female  05-11-1968         12           IT   29400            14250

     job_time  previous_experience minority
0        8.17                  NaN       No
1        8.17                 3.00       No
2        8.17                31.75       No
3        8.17                15.83       No
4        8.17                11.50       No
..        ...                  ...      ...
469      5.33                 5.75      Yes
470      5.33                 2.67      Yes
471      5.25                 3.83       No
472      5.25                11.58       No
473      5.25                 0.75       No

[474 rows x 10 columns]>

In [ ]:
df.